spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ojsystem?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
#    password: rpz2020^
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 3530077842@qq.com #QQ邮箱
    password: gycvhdmjgohiciac #客户端授权码
    protocol: smtp #发送邮件协议
    properties.smtp.ssl.enable: true  #开启ssl安全连接
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

server:
  port: 10087
